
export const GENRES: Array<string> = [
  "ACTION",
  "ADVENTURE",
  "COMEDY",
  "DRAMA",
  "FANTASY",
  "HISTORICAL FICTION",
  "ROMANCE",
  "SCIENCE FICTION",
  "SUSPENCE",
  "THRILLER",
];

export const ACTIONS: Array<string> = [
  "Walking through a forest",
  "Opening a mysterious door",
  "Finding a hidden note",
  "Receiving an unexpected letter",
  "Meeting a stranger",
  "Getting lost in a city",
  "Attending a party",
  "Discovering a secret room",
  "Chasing after a thief",
  "Witnessing a crime",
  "Helping a wounded animal",
  "Hearing a strange noise",
  "Following a map",
  "Finding a hidden treasure",
  "Climbing a mountain",
  "Escaping from danger",
  "Solving a puzzle",
  "Encountering a ghost",
  "Falling in love",
  "Breaking a curse",
  "Learning a new skill",
  "Losing a valuable item",
  "Making a difficult decision",
  "Standing up to a bully",
  "Searching for a lost person",
  "Investigating a mystery",
  "Going on a journey",
  "Facing a fear",
  "Discovering a lie",
  "Reuniting with a long-lost friend",
  "Protecting a secret",
  "Rescuing someone in trouble",
  "Planning a heist",
  "Preparing for a battle",
  "Dealing with a betrayal",
  "Receiving a prophecy",
  "Making an important speech",
  "Competing in a contest",
  "Building something new",
  "Destroying an evil artifact",
  "Escaping from captivity",
  "Negotiating a peace treaty",
  "Exploring a new world",
  "Finding a magical object",
  "Saving a kingdom",
  "Joining a rebellion",
  "Discovering one's true identity",
  "Overcoming an illness",
  "Making a new friend",
  "Losing someone close",
  "Writing a story",
  "Cooking a special meal",
  "Creating art",
  "Learning the truth",
  "Teaching someone a lesson",
  "Finding redemption",
  "Dealing with loss",
  "Standing up for justice",
  "Traveling to a distant land",
  "Helping a community",
  "Inventing something",
  "Meeting a mentor",
  "Forming an alliance",
  "Uncovering a conspiracy",
  "Surviving a disaster",
  "Finding hope",
  "Making a sacrifice",
  "Fighting a monster",
  "Discovering a new power",
  "Building a relationship",
  "Forgiving an enemy",
  "Taking a risk",
  "Following a dream",
  "Breaking the rules",
  "Finding inner strength",
  "Standing alone",
  "Facing a moral dilemma",
  "Losing faith",
  "Finding faith",
  "Protecting loved ones",
  "Making amends",
  "Changing the world",
  "Growing up",
  "Fulfilling a destiny",
  "Overcoming prejudice",
  "Seeking revenge",
  "Finding peace",
  "Solving a riddle",
  "Confronting a villain",
  "Uniting a divided group",
  "Creating a legacy",
  "Dealing with consequences",
  "Searching for meaning",
  "Encountering the supernatural",
  "Making a promise",
  "Breaking a promise",
  "Challenging authority",
  "Finding freedom",
  "Surviving the wilderness",
  "Facing the unknown ",
]

export const NAMES: Array<string> = [
"Amir",
"Ravi",
"Carlos",
"Hiroshi",
"Kwame",
"Ahmed",
"Malik",
"Wei",
"Jamal",
"Tariq",
"Arjun",
"Darnell",
"Javier",
"Ayaan",
"Kofi",
"Youssef",
"Dante",
"Farid",
"Rajesh",
"Mustafa",
"Darius",
"Juan",
"Samir",
"Omar",
"Zane",
"Akio",
"Jalen",
"Imran",
"Ismail",
"Kenji",
"Sanjay",
"Hassan",
"Daiki",
"Aisha",
"Priya",
"Yara",
"Leilani",
"Anika",
"Mei",
"Nia",
"Amara",
"Fatima",
"Sanaa",
"Imani",
"Kiara",
"Lila",
"Zara",
"Keiko",
"Lakshmi",
"Esme",
"Hana",
"Alina",
"Sade",
"Amina",
"Zuri",
"Yasmin",
"Kamala",
"Nadia",
"Nala",
"Amaya",
"Jada",
"Kiana",
"Nyla",
"Mahira",
"Noora",
"Layla",
"Alex",
"Jordan",
"Taylor",
"Casey",
"Morgan",
"Riley",
"Avery",
"Quinn",
"Peyton",
"Jamie",
"Cameron",
"Kai",
"Sage",
"Drew",
"Skyler",
"Reese",
"Devon",
"Ellis",
"Micah",
"Rowan",
"Bailey",
"Sidney",
"Harper",
"Dakota",
"Avery",
"Hayden",
"Logan",
"Kendall",
"Phoenix",
"Sam",
"Tatum",
"Blake",
"Robin",
"Alexis",
]

export const LINES: Array<string> = [
  "I never expected to see you here.",
"The stars look brighter tonight.",
"What do you mean, it's gone?",
"Sometimes, the truth is the hardest thing to accept.",
"Are you sure this is the right path?",
"I've been waiting for this moment all my life.",
"Please, don't tell anyone.",
"Why does it always rain when I'm sad?",
"I found something you need to see.",
"That wasn't part of the plan.",
"This place gives me the creeps.",
"Do you believe in fate?",
"Everything happens for a reason.",
"You can't hide from your past forever.",
"What if we just ran away?",
"I never wanted to hurt you.",
"There's a storm coming.",
"How can you be so calm?",
"I'm not who you think I am.",
"This isn't over yet.",
"Can you hear that?",
"I've got a bad feeling about this.",
"You don't understand what I've been through.",
"Let's make a deal.",
"Why didn't you tell me sooner?",
"I saw it with my own eyes.",
"What are you afraid of?",
"Don't look back.",
"I've heard stories about this place.",
"We can't stay here much longer.",
"You have to trust me.",
"It's not what it looks like.",
"There's no turning back now.",
"I wish things were different.",
"Do you remember the first time we met?",
"This is just the beginning.",
"You have no idea what you're dealing with.",
"I can't do this without you.",
"Why do you care so much?",
"There's something I need to tell you.",
"You're not alone.",
"What do we do now?",
"I've made a terrible mistake.",
"This changes everything.",
"I thought you were my friend.",
"We need to get out of here.",
"Sometimes, silence is the best answer.",
"Is this really happening?",
"You're stronger than you think.",
"Let's go home.",
"What did you expect?",
"I can't believe you did that.",
"Time is running out.",
"Who are you?",
"Don't worry, I've got your back.",
"What do you want from me?",
"I don't believe in coincidences.",
"You're braver than you know.",
"How did you find me?",
"What's your real name?",
"I won't let you down.",
"We have to keep moving.",
"You're my only hope.",
"I can't keep this secret any longer.",
"Why are you doing this?",
"It's a long story.",
"I need you to stay strong.",
"This is our chance.",
"I've been searching for you.",
"What are you hiding?",
"Don't say I didn't warn you.",
"You always know what to say.",
"I can't face this alone.",
"Do you think we'll make it?",
"This is your last chance.",
"You were right all along.",
"I don't have time for this.",
"We have to take a risk.",
"I can't believe it's over.",
"What if we fail?",
"I've seen enough.",
"This is harder than I thought.",
"There's no way out.",
"I knew you would come.",
"Let's find out.",
"You can't be serious.",
"I need to know the truth.",
"This place feels different.",
"What are we waiting for?",
"I'm not going anywhere.",
"We have to stick together.",
"This could be dangerous.",
"I never asked for this.",
"It's up to you now.",
"Why did you leave?",
"I have to go.",
"You deserve better.",
"This is a waste of time.",
"I can't believe I found you.",
"We'll figure it out.",
]